### PR TITLE
bandana vanity

### PR DESCRIPTION
**Pull request by cloudziq**
all done (98%;) and tested, 100 tris

config:
addvanity 5     "bandana"               "bandana"           "tag_headtop"       3   2       // face

Should I add a 'proj' folder too ??

### CODE REVIEW

**Comment by qreeves** [comment]
The 'proj' should be used when you want the vanity to fly off the player when they die, so that's up to you.

**Comment by cloudziq** [comment]
yeah, looking nice in game :), all ready now, enjoy :)

**Comment by TheAssassin** [comment]
You should consider adding screenshots to your PRs, that makes it easier for people to check out what you have been working on.

**Comment by cloudziq** [comment]
its just bandana vanity, the same as I presented in vanities topic on forums, all is done so I consider this one finished :)

http://i.imgur.com/9b9JPn6h.jpg
http://i.imgur.com/QRKFqmsh.jpg
http://i.imgur.com/PmS9lAeh.jpg

**Pull request merged**
