### PR TITLE
add 'cyber cat ears' vanity

### PR DESCRIPTION
**Pull request by V-ktor**
Add 'cyber cat ears' vanity.

### CODE REVIEW

**Review by no-lex — APPROVED** [review]
All looks correctly compressed and appears correctly configured, but perhaps slightly low-res. 
Seems OK to merge on the grounds of formatting however.

**Comment by V-ktor** [comment]
The other vanities seem to be low-res as well.
I scaled down the textures so I can also provide them in two times higher resolution if needed.

**Comment by no-lex** [comment]
Yeah, if you could provide double-res textures that would be better.

**Comment by qreeves** [comment]
Got the `vanities.cfg` entries for me to add?

**Comment by V-ktor** [comment]
I opened a pull request https://github.com/red-eclipse/base/pull/902

**Comment by qreeves** [comment]
Haha, thanks. You don't need to actually do a pull request on base though, just putting the entries in your original post on this issue is fine 😄

**Pull request merged**
